name: uxux
favicon: null
layout_spectrum: 0.8225147800985724
typography_spectrum: 0.793953132815659
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.9920234552118927
  lightness: 0.39649221021682024
  saturation: 0.23558512679301202
  rhythmicContrast: 0.8720237496308982
purpose: []
